services:
  - type: web
    name: flask-pharma-dashboard
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn wsgi:application --worker-class eventlet -w 1 --timeout 120 --keep-alive 65 --log-level debug --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: main.py
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: PORT
        value: "10000"
      - key: SQLALCHEMY_POOL_SIZE
        value: "20"
      - key: SQLALCHEMY_MAX_OVERFLOW
        value: "10"
      - key: SQLALCHEMY_POOL_TIMEOUT
        value: "30"
      - key: SQLALCHEMY_POOL_RECYCLE
        value: "60"
      - key: GUNICORN_TIMEOUT
        value: "120"
      - key: GUNICORN_KEEP_ALIVE
        value: "65"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: EVENTLET_DEBUG
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: flask-dashboard-db
          property: connectionString
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
    healthCheckPath: /about
    autoDeploy: true

  - type: postgres
    name: flask-dashboard-db
    ipAllowList: []
    plan: free 